# Generated by Django 5.2 on 2025-05-21 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_review_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='liked_by',
            new_name='likes',
        ),
    ]
