# Generated by Django 5.2 on 2025-04-25 15:18

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'), # Se modifica el campo 'content' del modelo Blog por CKEditor5Field para permitir la edicion de texto enriquecido
        ),
    ]
